services:
  service1: 
    build:
      context: ./XRayAPI
      target: xray-server
    stop_signal: SIGINT
    ports: 
      - '8000:8000'

  service2: 
    build:
      context: ./HeartDiseaseApi
      target: heart-disease-server
    stop_signal: SIGINT
    ports: 
      - '8001:8001'

  service3: 
    build:
      context: ./BrainMRIAPI
      target: mri-server
    stop_signal: SIGINT
    ports: 
      - '4000:4000'
