services:
  xrayapi: 
    build:
      context: ./XRayAPI
      target: xray-server
    stop_signal: SIGINT
    ports: 
      - '8000:8000'

  heartdiseaseapi: 
    build:
      context: ./HeartDiseaseApi
      target: heart-disease-server
    stop_signal: SIGINT
    ports: 
      - '8001:8001'

  mriapi: 
    build:
      context: ./BrainMRIAPI
      target: mri-server
    stop_signal: SIGINT
    ports: 
      - '4000:4000'
