services:
  service1: 
    build:
      context: .
      target: ./xray-server
    stop_signal: SIGINT
    ports: 
      - '8000:8000'

  service2: 
    build:
      context: .
      target: ./heartdesiase-server
    stop_signal: SIGINT
    ports: 
      - '7000:7000'

  service3: 
    build:
      context: .
      target: ./mri-server
    stop_signal: SIGINT
    ports: 
      - '4000:4000'
